# Generated by Django 2.2.10 on 2022-03-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
