# Generated by Django 3.2.10 on 2024-03-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_auto_20220313_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
