# Generated by Django 3.2.10 on 2024-05-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='play_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='viewers_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='genre',
            table='genre',
        ),
        migrations.AlterModelTable(
            name='movie',
            table='movie',
        ),
        migrations.AlterModelTable(
            name='movie_hot',
            table='movie_hot',
        ),
        migrations.AlterModelTable(
            name='movie_rating',
            table='movie_rating',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='usertype',
            table='user_type',
        ),
    ]
